-- DROP SCHEMA tgame;

CREATE SCHEMA tgame AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA tgame IS 'standard tgame schema';

-- DROP TYPE tgame."admin_role";

CREATE TYPE tgame."admin_role" AS ENUM (
	'sys admin',
	'sys mgr',
	'sys user');

-- DROP SEQUENCE tgame.event_calendar_id_seq;

CREATE SEQUENCE tgame.event_calendar_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tgame.facility_geographics_id_seq;

CREATE SEQUENCE tgame.facility_geographics_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tgame.lead_score_params_param_id_seq;

CREATE SEQUENCE tgame.lead_score_params_param_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tgame.saved_posts_id_seq;

CREATE SEQUENCE tgame.saved_posts_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE tgame.tgx_leads_leadid_seq;

CREATE SEQUENCE tgame.tgx_leads_leadid_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- tgame.event_calendar definition

-- Drop table

-- DROP TABLE tgame.event_calendar;

CREATE TABLE tgame.event_calendar (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id text NOT NULL,
	post_id text NOT NULL,
	event_date timestamptz NOT NULL,
	notes text NULL,
	created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
	calendar_id int4 DEFAULT 0 NOT NULL,
	CONSTRAINT event_calendar_pkey PRIMARY KEY (id)
);
ALTER TABLE tgame.event_calendar ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY "Enable insert for all users" ON tgame.event_calendar
 AS PERMISSIVE
 FOR INSERT
 WITH CHECK (true);
CREATE POLICY "Enable read access for all users" ON tgame.event_calendar
 AS PERMISSIVE
 FOR SELECT
 USING (true);
CREATE POLICY "Enable delete and update for all users" ON tgame.event_calendar
 AS PERMISSIVE
 FOR ALL
 USING (true);


-- tgame.facility_geographics definition

-- Drop table

-- DROP TABLE tgame.facility_geographics;

CREATE TABLE tgame.facility_geographics (
	id serial4 NOT NULL,
	facility_id text NULL,
	address_line1 varchar(255) NULL,
	address_line2 varchar(255) NULL,
	city varchar(100) NULL,
	state varchar(50) NULL,
	zip_code varchar(20) NULL,
	county varchar(100) NULL,
	state_region varchar(50) NULL,
	latitude numeric(9, 6) NULL,
	longitude numeric(9, 6) NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT facility_geographics_pkey PRIMARY KEY (id),
	CONSTRAINT unique_facility_location UNIQUE (address_line1, zip_code)
);
ALTER TABLE tgame.facility_geographics ENABLE ROW LEVEL SECURITY;


-- tgame.facility_hq definition

-- Drop table

-- DROP TABLE tgame.facility_hq;

CREATE TABLE tgame.facility_hq (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	hq_name text NOT NULL,
	hq_address text NULL,
	tax_id text NULL,
	website text NULL,
	CONSTRAINT facility_parent_entity_name_key UNIQUE (hq_name),
	CONSTRAINT facility_parent_pkey PRIMARY KEY (id)
);
ALTER TABLE tgame.facility_hq ENABLE ROW LEVEL SECURITY;


-- tgame.facility_mgmt_co definition

-- Drop table

-- DROP TABLE tgame.facility_mgmt_co;

CREATE TABLE tgame.facility_mgmt_co (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	company_name text NOT NULL,
	contact_person text NULL,
	operating_license text NULL,
	CONSTRAINT facility_mgmt_co_company_name_key UNIQUE (company_name),
	CONSTRAINT facility_mgmt_co_pkey PRIMARY KEY (id)
);
ALTER TABLE tgame.facility_mgmt_co ENABLE ROW LEVEL SECURITY;


-- tgame.facility_types definition

-- Drop table

-- DROP TABLE tgame.facility_types;

CREATE TABLE tgame.facility_types (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	category text NOT NULL,
	type_name text NOT NULL,
	abbreviation text NULL,
	description text NULL,
	mds_required bool DEFAULT false NULL,
	compliance_level text NULL,
	CONSTRAINT facility_types_compliance_level_check CHECK ((compliance_level = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text]))),
	CONSTRAINT facility_types_pkey PRIMARY KEY (id),
	CONSTRAINT facility_types_type_name_key UNIQUE (type_name)
);
ALTER TABLE tgame.facility_types ENABLE ROW LEVEL SECURITY;


-- tgame.profiles definition

-- Drop table

-- DROP TABLE tgame.profiles;

CREATE TABLE tgame.profiles (
	id text NOT NULL,
	facility_name text NULL,
	admin_name text NULL,
	license_number text NULL,
	npi_number text NULL,
	facility_address text NULL,
	updated_at timestamptz NULL,
	email text NULL,
	subscription_status text DEFAULT 'trial'::text NULL,
	CONSTRAINT profiles_pkey PRIMARY KEY (id)
);
ALTER TABLE tgame.profiles ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY "Users can manage their own profile" ON tgame.profiles
 AS PERMISSIVE
 FOR ALL
 USING (((auth.uid())::text = id));


-- tgame.role_master definition

-- Drop table

-- DROP TABLE tgame.role_master;

CREATE TABLE tgame.role_master (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	role_name text NOT NULL,
	clearance_level int4 NOT NULL,
	"zone" text NOT NULL,
	CONSTRAINT role_master_pkey PRIMARY KEY (id),
	CONSTRAINT role_master_role_name_key UNIQUE (role_name)
);
ALTER TABLE tgame.role_master ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY "Authenticated users can view role master" ON tgame.role_master
 AS PERMISSIVE
 FOR SELECT
 USING ((clerk_user_id() IS NOT NULL));


-- tgame.saved_posts definition

-- Drop table

-- DROP TABLE tgame.saved_posts;

CREATE TABLE tgame.saved_posts (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id text NOT NULL,
	post_id text NOT NULL,
	created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
	CONSTRAINT saved_posts_pkey PRIMARY KEY (id),
	CONSTRAINT saved_posts_user_id_post_id_key UNIQUE (user_id, post_id)
);
ALTER TABLE tgame.saved_posts ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY "Allow tgame insert access" ON tgame.saved_posts
 AS PERMISSIVE
 FOR INSERT
 WITH CHECK (true);
CREATE POLICY "Allow individual read access" ON tgame.saved_posts
 AS PERMISSIVE
 FOR SELECT
 USING (true);


-- tgame.subscribers definition

-- Drop table

-- DROP TABLE tgame.subscribers;

CREATE TABLE tgame.subscribers (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	email text NOT NULL,
	full_name text NULL,
	status text DEFAULT 'active'::text NULL,
	"source" text DEFAULT 'join_page'::text NULL,
	created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
	CONSTRAINT subscribers_email_key UNIQUE (email),
	CONSTRAINT subscribers_pkey PRIMARY KEY (id)
);
ALTER TABLE tgame.subscribers ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY "Enable insert for service role only" ON tgame.subscribers
 AS PERMISSIVE
 FOR INSERT
 TO service_role
 WITH CHECK (true);
CREATE POLICY "Restrict all tgame reads" ON tgame.subscribers
 AS PERMISSIVE
 FOR SELECT
 USING (false);
CREATE POLICY "Enable full access for authenticated admins" ON tgame.subscribers
 AS PERMISSIVE
 FOR ALL
 TO authenticated
 USING (((auth.jwt() ->> 'email'::text) = 'your-admin-email@siemens.com'::text));


-- tgame.support_tickets definition

-- Drop table

-- DROP TABLE tgame.support_tickets;

CREATE TABLE tgame.support_tickets (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	user_id text NOT NULL,
	email text NOT NULL,
	category text NOT NULL,
	message text NOT NULL,
	status text DEFAULT 'open'::text NULL,
	CONSTRAINT support_tickets_pkey PRIMARY KEY (id)
);
ALTER TABLE tgame.support_tickets ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY "Users can view their own tickets" ON tgame.support_tickets
 AS PERMISSIVE
 FOR SELECT
 USING (((auth.uid())::text = user_id));
CREATE POLICY "Users can submit tickets" ON tgame.support_tickets
 AS PERMISSIVE
 FOR INSERT
 WITH CHECK (true);


-- tgame.tgx_leads definition

-- Drop table

-- DROP TABLE tgame.tgx_leads;

CREATE TABLE tgame.tgx_leads (
	leadid int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	lead_type varchar(255) NULL,
	lead_name varchar(255) NULL,
	address varchar(255) NULL,
	phone_number varchar(50) NULL,
	email_address varchar(255) NULL,
	website_url varchar(255) NULL,
	contact_name varchar(255) NULL,
	lead_desc text NULL,
	dt_created timestamptz DEFAULT now() NULL,
	last_touch_dt timestamptz NULL,
	touch_channel varchar(50) NULL,
	is_active bool DEFAULT true NULL,
	notes text NULL,
	lead_score int4 DEFAULT 0 NULL,
	facebook_url varchar(255) NULL,
	linkedin_url varchar(255) NULL,
	instagram_url varchar(255) NULL,
	twitter_url varchar(255) NULL,
	city varchar NULL,
	county varchar NULL,
	state varchar NULL,
	zip_code varchar NULL,
	lead_source text NULL,
	CONSTRAINT tgx_leads_pkey PRIMARY KEY (leadid)
);
ALTER TABLE tgame.tgx_leads ENABLE ROW LEVEL SECURITY;


-- tgame.facility_registry definition

-- Drop table

-- DROP TABLE tgame.facility_registry;

CREATE TABLE tgame.facility_registry (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	facility_name text NOT NULL,
	facility_id text NOT NULL,
	address_line text NULL,
	city text NULL,
	state text NULL,
	zip_code text NULL,
	status text DEFAULT 'trial'::text NULL,
	bed_count int4 NULL,
	primary_contact_id text NULL,
	subscription_tier text DEFAULT 'pro'::text NULL,
	website text NULL,
	phone text NULL,
	email text NULL,
	hq_id uuid NULL,
	mgmt_id uuid NULL,
	type_id uuid NULL,
	CONSTRAINT facility_registry_facility_id_key UNIQUE (facility_id),
	CONSTRAINT facility_registry_pkey PRIMARY KEY (id),
	CONSTRAINT facility_registry_status_check CHECK ((status = ANY (ARRAY['active'::text, 'trial'::text, 'onboarding'::text, 'suspended'::text]))),
	CONSTRAINT unique_physical_location UNIQUE (address_line, city, zip_code),
	CONSTRAINT facility_registry_mgmt_id_fkey FOREIGN KEY (mgmt_id) REFERENCES tgame.facility_mgmt_co(id),
	CONSTRAINT facility_registry_parent_id_fkey FOREIGN KEY (hq_id) REFERENCES tgame.facility_hq(id),
	CONSTRAINT facility_registry_primary_contact_id_fkey FOREIGN KEY (primary_contact_id) REFERENCES tgame.profiles(id),
	CONSTRAINT facility_registry_type_id_fkey FOREIGN KEY (type_id) REFERENCES tgame.facility_types(id)
);
CREATE INDEX idx_facility_id ON tgame.facility_registry USING btree (facility_id);
ALTER TABLE tgame.facility_registry ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY "Internal Access Only" ON tgame.facility_registry
 AS PERMISSIVE
 FOR ALL
 USING ((EXISTS ( SELECT 1
   FROM (user_roles ur
     JOIN role_master rm ON ((ur.role_id = rm.id)))
  WHERE ((ur.user_id = clerk_user_id()) AND (rm.zone = 'internal'::text)))));


-- tgame.lead_score_params definition

-- Drop table

-- DROP TABLE tgame.lead_score_params;

CREATE TABLE tgame.lead_score_params (
	param_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	lead_id int4 NULL,
	param_name varchar(255) NOT NULL,
	param_value numeric NULL,
	param_desc text NULL,
	dt_modified timestamptz DEFAULT now() NULL,
	CONSTRAINT lead_score_params_pkey PRIMARY KEY (param_id),
	CONSTRAINT lead_score_params_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES tgame.tgx_leads(leadid) ON DELETE CASCADE
);

-- Table Triggers

create trigger update_lead_score_params_modtime before
update
    on
    tgame.lead_score_params for each row execute function update_modified_column();
ALTER TABLE tgame.lead_score_params ENABLE ROW LEVEL SECURITY;


-- tgame.user_roles definition

-- Drop table

-- DROP TABLE tgame.user_roles;

CREATE TABLE tgame.user_roles (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	user_id text NOT NULL,
	email text NULL,
	role_id uuid NULL,
	CONSTRAINT user_roles_pkey PRIMARY KEY (id),
	CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES tgame.role_master(id)
);
ALTER TABLE tgame.user_roles ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY "Service role only" ON tgame.user_roles
 AS PERMISSIVE
 FOR ALL
 USING (false)
 WITH CHECK (false);
CREATE POLICY "Users can view own roles" ON tgame.user_roles
 AS PERMISSIVE
 FOR SELECT
 USING ((user_id = clerk_user_id()));


-- tgame.facility_contacts definition

-- Drop table

-- DROP TABLE tgame.facility_contacts;

CREATE TABLE tgame.facility_contacts (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	facility_id text NULL,
	profile_id text NULL,
	job_title text NULL,
	is_primary bool DEFAULT false NULL,
	created_at timestamptz DEFAULT now() NULL,
	contact_name text NULL,
	contact_phone text NULL,
	contact_email text NULL,
	linkedin text NULL,
	facebook text NULL,
	twitter text NULL,
	instagram text NULL,
	is_active bool DEFAULT true NULL,
	lead_status text DEFAULT 'prospect'::text NULL,
	CONSTRAINT facility_contacts_lead_status_check CHECK ((lead_status = ANY (ARRAY['prospect'::text, 'warm'::text, 'contacted'::text, 'converted'::text, 'inactive'::text]))),
	CONSTRAINT facility_contacts_pkey PRIMARY KEY (id),
	CONSTRAINT unique_facility_contact_identity UNIQUE (contact_name, contact_phone, contact_email, facility_id),
	CONSTRAINT facility_contacts_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES tgame.facility_registry(facility_id),
	CONSTRAINT facility_contacts_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES tgame.profiles(id)
);
CREATE INDEX idx_contacts_name ON tgame.facility_contacts USING btree (contact_name);
ALTER TABLE tgame.facility_contacts ENABLE ROW LEVEL SECURITY;



-- DROP FUNCTION tgame.clerk_user_id();

CREATE OR REPLACE FUNCTION tgame.clerk_user_id()
 RETURNS text
 LANGUAGE sql
 STABLE
AS $function$
  SELECT nullif(current_setting('request.jwt.claims', true)::json->>'sub', '')::text;
$function$
;

-- DROP FUNCTION tgame.update_modified_column();

CREATE OR REPLACE FUNCTION tgame.update_modified_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.dt_modified = NOW();
    RETURN NEW;
END;
$function$
;