export interface GameActivity {
  id: string
  title: string
  description: string
  videoUrl: string
  platform: 'youtube' | 'tiktok' | 'instagram' | 'linkedin' | 'facebook'
  embedId: string
  category: 'memory' | 'movement' | 'trivia' | 'music' | 'creative' | 'social'
  mobility: 'all' | 'seated' | 'standing'
  playersMin: number
  playersMax: number
  durationMin: number
  gearUrl: string
  gearCost: string
  status: 'draft' | 'pending' | 'live'
  slug: string
}

export const initialGames: GameActivity[] = [
  {
    id: '1',
    title: 'Human Bowling — Care Home Edition',
    description: 'Residents form two teams. Lightweight foam balls are rolled down a corridor toward standing plastic pins or bottles. Encourages gentle competition and laughs.',
    videoUrl: 'https://www.youtube.com/watch?v=eqe_LMju6nQ',
    platform: 'youtube',
    embedId: 'eqe_LMju6nQ',
    category: 'movement',
    mobility: 'seated',
    playersMin: 6,
    playersMax: 20,
    durationMin: 20,
    gearUrl: 'https://www.amazon.com/s?k=giant+plastic+bowling+set',
    gearCost: '~$18',
    status: 'live',
    slug: 'human-bowling-care-home'
  },
  {
    id: '2',
    title: 'Name That Tune — Decade Challenge',
    description: 'Play instrumental or original hits from the 1950s and 60s. Residents buzz in or raise hands to guess the song name or artist for points.',
    videoUrl: 'https://www.tiktok.com/@seniorsjoy/video/7123456789012345678',
    platform: 'tiktok',
    embedId: '7123456789012345678',
    category: 'music',
    mobility: 'all',
    playersMin: 4,
    playersMax: 12,
    durationMin: 30,
    gearUrl: 'https://www.amazon.com/s?k=bluetooth+party+speaker',
    gearCost: '~$45',
    status: 'live',
    slug: 'name-that-tune-decade-challenge'
  },
  {
    id: '3',
    title: 'Team Trivia — 1960s & 70s History',
    description: 'A fun team-based trivia challenge highlighting major historical milestones, pop culture, and classic movies from the golden era.',
    videoUrl: 'https://www.instagram.com/p/Co123456789/',
    platform: 'instagram',
    embedId: 'Co123456789',
    category: 'memory',
    mobility: 'all',
    playersMin: 6,
    playersMax: 30,
    durationMin: 45,
    gearUrl: 'https://www.amazon.com/s?k=retro+trivia+cards+game',
    gearCost: '~$15',
    status: 'live',
    slug: 'team-trivia-1960s-70s-history'
  },
  {
    id: '4',
    title: 'Balloon Volleyball — Seated Action',
    description: 'A gentle movement activity using a soft balloon and a low string net. Improves hand-eye coordination and core strength from a comfortable seated position.',
    videoUrl: 'https://www.youtube.com/watch?v=balloon-volleyball',
    platform: 'youtube',
    embedId: 'balloon-volleyball',
    category: 'movement',
    mobility: 'seated',
    playersMin: 4,
    playersMax: 16,
    durationMin: 15,
    gearUrl: 'https://www.amazon.com/s?k=colorful+balloons+and+hand+pump',
    gearCost: '~$10',
    status: 'live',
    slug: 'balloon-volleyball-seated'
  },
  {
    id: '5',
    title: 'Giant Jigsaw Speed Race',
    description: 'Teams of residents collaborate to complete a large-piece puzzle. Promotes hand agility, team problem solving, and visual recognition.',
    videoUrl: 'https://www.youtube.com/watch?v=puzzle-race',
    platform: 'youtube',
    embedId: 'puzzle-race',
    category: 'creative',
    mobility: 'all',
    playersMin: 2,
    playersMax: 8,
    durationMin: 25,
    gearUrl: 'https://www.amazon.com/s?k=giant+floor+puzzle+300+pieces',
    gearCost: '~$20',
    status: 'live',
    slug: 'giant-jigsaw-speed-race'
  },
  {
    id: '6',
    title: 'Noodle Hockey — Chair Games',
    description: 'Seated players use pool noodles to guide a beach ball into the opposing team net. Extremely fun and generates lots of laughter.',
    videoUrl: 'https://www.youtube.com/watch?v=noodle-hockey',
    platform: 'youtube',
    embedId: 'noodle-hockey',
    category: 'movement',
    mobility: 'seated',
    playersMin: 6,
    playersMax: 14,
    durationMin: 20,
    gearUrl: 'https://www.amazon.com/s?k=pool+noodles+and+beach+ball',
    gearCost: '~$14',
    status: 'live',
    slug: 'noodle-hockey-chair-games'
  },
  {
    id: '7',
    title: 'Classic Bingo — Retro Cards',
    description: 'A timeless favorite. Traditional slide cards or large-print markers are used to coordinate number matching in groups.',
    videoUrl: 'https://www.youtube.com/watch?v=classic-bingo',
    platform: 'youtube',
    embedId: 'classic-bingo',
    category: 'social',
    mobility: 'all',
    playersMin: 5,
    playersMax: 40,
    durationMin: 40,
    gearUrl: 'https://www.amazon.com/s?k=large+print+bingo+cards',
    gearCost: '~$25',
    status: 'live',
    slug: 'classic-bingo-retro-cards'
  },
  {
    id: '8',
    title: 'Pass The Parcel — Memory Edition',
    description: 'A classic game with a twist: under each layer of wrapping paper is a fun trivia card or a prompt to recall a nostalgic childhood memory.',
    videoUrl: 'https://www.youtube.com/watch?v=pass-parcel',
    platform: 'youtube',
    embedId: 'pass-parcel',
    category: 'memory',
    mobility: 'seated',
    playersMin: 4,
    playersMax: 12,
    durationMin: 25,
    gearUrl: 'https://www.amazon.com/s?k=wrapping+paper+rolls',
    gearCost: '~$8',
    status: 'live',
    slug: 'pass-parcel-memory-edition'
  },
  {
    id: '9',
    title: 'Group Painting — Watercolor Landscapes',
    description: 'Guided painting session using easy watercolors. Perfect for encouraging creativity and fine motor coordination.',
    videoUrl: 'https://www.youtube.com/watch?v=watercolor-landscape',
    platform: 'youtube',
    embedId: 'watercolor-landscape',
    category: 'creative',
    mobility: 'all',
    playersMin: 3,
    playersMax: 10,
    durationMin: 50,
    gearUrl: 'https://www.amazon.com/s?k=watercolor-paint-set-washable',
    gearCost: '~$22',
    status: 'live',
    slug: 'group-painting-watercolor'
  },
  {
    id: '10',
    title: 'Indoor Ring Toss Tournament',
    description: 'Gentle target tossing game that can be adjusted in distance to match different physical abilities. Generates fun competitive spirit.',
    videoUrl: 'https://www.youtube.com/watch?v=ring-toss',
    platform: 'youtube',
    embedId: 'ring-toss',
    category: 'movement',
    mobility: 'all',
    playersMin: 4,
    playersMax: 12,
    durationMin: 15,
    gearUrl: 'https://www.amazon.com/s?k=wooden+ring+toss+game',
    gearCost: '~$16',
    status: 'live',
    slug: 'indoor-ring-toss-tournament'
  },
  {
    id: '11',
    title: 'Oldies Sing-Along Karaoke',
    description: 'Chant along to historical classics from Sinatra, Elvis, and Judy Garland. Extremely beneficial for memory retrieval and respiratory strength.',
    videoUrl: 'https://www.youtube.com/watch?v=sing-along-karaoke',
    platform: 'youtube',
    embedId: 'sing-along-karaoke',
    category: 'music',
    mobility: 'all',
    playersMin: 5,
    playersMax: 30,
    durationMin: 40,
    gearUrl: 'https://www.amazon.com/s?k=singalong+dvd+for+seniors',
    gearCost: '~$19',
    status: 'live',
    slug: 'oldies-sing-along-karaoke'
  },
  {
    id: '12',
    title: 'Word Association Relay',
    description: 'Pass the talking stick and declare a associated word within 5 seconds. Exercises prompt cognitive recall and verbal processing.',
    videoUrl: 'https://www.youtube.com/watch?v=word-relay',
    platform: 'youtube',
    embedId: 'word-relay',
    category: 'trivia',
    mobility: 'seated',
    playersMin: 4,
    playersMax: 15,
    durationMin: 15,
    gearUrl: 'https://www.amazon.com/s?k=wooden+talking+stick',
    gearCost: '~$10',
    status: 'live',
    slug: 'word-association-relay'
  },
  {
    id: '13',
    title: 'Bean Bag Cornhole Match',
    description: 'A scale-down version of cornhole boards suitable for indoor play or wheelchair tables. Keeps hand aiming active.',
    videoUrl: 'https://www.youtube.com/watch?v=cornhole-match',
    platform: 'youtube',
    embedId: 'cornhole-match',
    category: 'movement',
    mobility: 'seated',
    playersMin: 4,
    playersMax: 10,
    durationMin: 30,
    gearUrl: 'https://www.amazon.com/s?k=indoor+mini+cornhole+set',
    gearCost: '~$24',
    status: 'live',
    slug: 'bean-bag-cornhole-match'
  },
  {
    id: '14',
    title: 'Clay Sculpting & Storytelling',
    description: 'Residents sculpt simple items from lightweight air-dry clay and tell a short memory or story inspired by what they built.',
    videoUrl: 'https://www.youtube.com/watch?v=clay-sculpting',
    platform: 'youtube',
    embedId: 'clay-sculpting',
    category: 'creative',
    mobility: 'all',
    playersMin: 3,
    playersMax: 8,
    durationMin: 45,
    gearUrl: 'https://www.amazon.com/s?k=air+dry+clay+kit+non+toxic',
    gearCost: '~$12',
    status: 'live',
    slug: 'clay-sculpting-storytelling'
  },
  {
    id: '15',
    title: 'Memory Card Matching Race',
    description: 'Teams work sequentially to match oversized cards spread on tables. A highly effective and social cognitive exercise.',
    videoUrl: 'https://www.youtube.com/watch?v=memory-card-matching',
    platform: 'youtube',
    embedId: 'memory-card-matching',
    category: 'memory',
    mobility: 'all',
    playersMin: 2,
    playersMax: 8,
    durationMin: 20,
    gearUrl: 'https://www.amazon.com/s?k=giant+memory+matching+cards+seniors',
    gearCost: '~$13',
    status: 'live',
    slug: 'memory-card-matching-race'
  }
]
